import phoneShow from './modules/phoneShow';
import menuShow from './modules/menuShow';
import menuScroll from './modules/menuScroll';
import phonesMask from './modules/phonesMask';
import sendForm from './modules/sendForm';
import linkPravicy from './modules/linkPravicy';
import formulaHint from './modules/formulaHint';
import formulaSlider from './modules/formulaSlider';
import repairSlider from './modules/repairSlider';
import portfolioDesctop from './modules/portfolioDesctop';
import portfolioMobile from './modules/portfolioMobile';
import portfolioPopUp from './modules/portfolioPopUp';
import transparencySlider from './modules/transparencySlider';
import transparencyPopUp from './modules/transparencyPopUp';
import problemsHint from './modules/problemsHint';
import problemsSlider from './modules/problemsSlider';
import designTabs from './modules/designTabs';
import consultButton from './modules/consultButton';
import review from './modules/review';
import scheme from './modules/scheme';
import accordion from './modules/accordion';
import partners from './modules/partners';
import service from './modules/service';

phoneShow();
menuShow();
menuScroll();
phonesMask();
sendForm();
linkPravicy();
formulaHint();
formulaSlider();
repairSlider();
portfolioDesctop();
portfolioMobile();
portfolioPopUp();
transparencySlider();
transparencyPopUp();
problemsHint();
problemsSlider();
designTabs();
consultButton();
review();
scheme();
accordion();
partners();
service();
